### ISSUE TITLE
03-Composed-model Setup.sh failed getting connectionString

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-ai-document-intelligence#13]
**Describe the bug**

**To Reproduce**
when executing bash setup.sh the script failed getting the connectionString, complaining about a non existent resource group 

![image](https://github.com/MicrosoftLearning/mslearn-ai-document-intelligence/assets/64772417/abe4f13a-d7e8-4cba-ba55-fb27b8e27116)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ivorb** [comment]
@unaihuete93 in the instructions, line 33, we instruct you to use `setup.ps1` which has the appropriate updates - the `.sh` was from a previous iteration. I'll remove the file so there's no confusion, thanks for pointing it out!

**Comment by unaihuete93** [comment]
Sorry if I missed the details, I was following the Learn module (not the instructions in the repo) https://learn.microsoft.com/en-gb/training/modules/create-composed-form-recognizer-model/4-exercise-model
![image](https://github.com/MicrosoftLearning/mslearn-ai-document-intelligence/assets/64772417/027b33dc-e3e3-46ef-a1e7-08e30e1fdf22)

**Comment by ivorb** [comment]
hmm there seems to be a mismatch - I replaced that file last week, but it appears it never published. My mistake, I'll chase that down. Thanks! gonna merge the PR for now, and I'll figure out the update issue
