### ISSUE TITLE
Incorrect MS Learn link

### ISSUE THREAD

**Issue by Humza-S** [MicrosoftLearning/mslearn-ai-document-intelligence#15]
MS Learn Enrich AI Search Index Link Discrepancy

**Description of Bug**
When coming from this link of an [MS Learn Exercise](https://microsoftlearning.github.io/mslearn-knowledge-mining/Instructions/Exercises/04-exercise-enrich-cognitive-custom-classes.html) then when the user clicks Azure Deploy, it does not work. Additionally, the azure deploy model within this repo does not produce the same results as on the webpage.

**To Reproduce**
1. Go to link provided
2. Scroll down and click Deploy to Azure
3. First part of the bug is here: incorrect link to github resource
4. If the user manages to find the azure deploy resource in the github repo, then that azuredeploy.json file also does not work

**Expected behavior**
Link should be correct on MS Learn website.
Azure Deploy resource should build.

**Comment by Humza-S** [comment]
Update: Just found a fix to the problem.

1. Go [here](https://github.com/MicrosoftLearning/mslearn-knowledge-mining/tree/main/Labfiles/04-enrich-custom-classes)
2. Download the zip
3. Unzip file
4. Go to azure portal and create a spec template
5. import template from the unizpped file (azuredeploy.json)
6. Finish creating template in Resource Group and Region where you want to deploy resources
7. once templated is created then go to the template page and hit Deploy and you can then follow the lecture.


Will leave it to Author to mark it as close as we still need MS Learn to update the link.

**Comment by ivorb** [comment]
fixed this in the appropriate repo
