### ISSUE TITLE
Read API --> language output format for recent API version

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-ai-document-intelligence#18]
**Describe the bug**
Screenshot shown in the following line may be updated. Latest API (used by default by students) shows the following output for language 
<img width="1232" alt="image" src="https://github.com/MicrosoftLearning/mslearn-ai-document-intelligence/assets/64772417/7420f412-e8f0-4d15-9738-69bbc891d024">
We may need to stick to an API version when testing it  or update the screenshot 

**To Reproduce**
1. Go to ['Screenshot'](https://github.com/MicrosoftLearning/mslearn-ai-document-intelligence/blob/e4c7ed8e69a606c7fa3be0d3a38ed819194eaa2d/Instructions/Exercises/01-use-prebuilt-models.md?plain=1#L45)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ivorb** [comment]
thanks for reporting. fixed with [bb3bb24](https://github.com/MicrosoftLearning/mslearn-ai-document-intelligence/commit/bb3bb249dd8d8c1e1446cee426a3dd4a73f92a08)
