### ISSUE TITLE
Url to PDF is incorrect

### ISSUE THREAD

**Issue by adamkimsft** [MicrosoftLearning/mslearn-ai-document-intelligence#5]
https://github.com/MicrosoftLearning/mslearn-ai-document-intelligence/blob/main/Labfiles/01-prebuild-models/starter/invoicereader/C-Sharp/Program.cs

url should point to '...raw/main/LabFiles..." instead of "...blob/main/LabFiles..." since we need the PDF document and not the Git UI frame for the PDF document.

**Comment by ivorb** [comment]
It was intended that you can just view it at that location, the clone of the repo is what gets you the file
