### ISSUE TITLE
02-custom-document-intelligence.md -- potential recent Azure behavioral change breaking setup.sh

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/mslearn-ai-document-intelligence#8]
I dont have a screenshot of the error handy, but just a bit earlier today I was working through this lab for the first time and I think a very recent Azure change has broken the setup.sh, in at least some Cloudslice scenarios: The script will run, and seem to complete, but if one scrolls back up through the output one will see an error w/message to the effect of 'container not found', and the 'sampleforms' is not populated.

I believe the recent change is related to public blob storage flag not working (or is disabled by default unless an org specifically allows it?) but in any case, I was able to get it to work fine by editing the setup.sh before running it.
 
Specifically: In file /Labfiles/02-custom-document-intelligence/setup.sh if we remove the '--public-access blob' in this line:

From:
az storage container create --account-name "ai102form$unique_id" --name sampleforms --public-access blob --auth-mode key --account-key "$AZURE_STORAGE_KEY" --output none

To:
az storage container create --account-name "ai102form$unique_id" --name sampleforms --auth-mode key --account-key "$AZURE_STORAGE_KEY" --output none

After making this change, I was able to complete the lab test end-to-end successfully.

**Comment by ivorb** [comment]
we actually went a different route in solving this issue - what you suggested would have worked, but we chose to enable public access in the storage account creation. thanks for reporting!

**Comment by ivorb** [comment]
actually not ready to close this one, will investigate

**Comment by ivorb** [comment]
publishing changes tomorrow, but changed the command to use `setup.cmd`, and a hosted VM, which fixes this issue and correctly populates the storage container. thanks for reporting!
